### ISSUE TITLE
Fetch multiple batch from the server

### ISSUE THREAD

**Issue by wywclmqf** [dmpalyvos/debs-2020-challenge-local#10]
Hi,

I was wondering if the grader accepted more than 2 requests in same time. I found there is a request limitation of the grader, since the request queue size is 2.

Best
Lee

**Comment by dmpalyvos** [comment]
Hi,

Could you elaborate on the issue a bit? What are you trying to achieve and what happens?

Kind Regards,
Dimitris

**Comment by wywclmqf** [comment]
Hi,

I set multiple threads to fetch data from grader. However the grader showed that "WARNING:waitress.queue:Task queue depth is 2". So is that means the grader can not accepted more than 2 requests in same time?

Best
Lee

**Comment by dmpalyvos** [comment]
Hi Lee,

The grader accepts only one request at the time and it cannot handle multiple concurrent requests from distinct threads. Notice, nonetheless, that the non-concurrent GET and POST requests do not need to be alternated. For instance, you could pipeline several GET requests if that strategy improves your performance (and the resulting grade).

Kind Regards,
Dimitris

**Comment by wywclmqf** [comment]
Hi Dimitris

Thank you very much, it's very helpful to us.

Thanks
Lee
