### ISSUE TITLE
Value 2.0

### ISSUE THREAD

**Issue by EthanTGo** [dmpalyvos/debs-2020-challenge-local#13]
For query2.py solution, I realize that we change the value to 2.0, if the event is late and I was wondering why we choose the value 2.0 or whether it was a placeholder.

**Comment by vincenzo-gulisano** [comment]
Hi,
there is no special reason. This is a sample baseline that does not wait for any late arriving data and replaces missing data with 2.0. The baselines for Query 1 and Query 2 are only given to show participants how to retrieve data and return results.
