### ISSUE TITLE
In Q2, Why Padding Out of Order Data with 2

### ISSUE THREAD

**Issue by Zongshun96** [dmpalyvos/debs-2020-challenge-local#14]
https://github.com/dmpalyvos/debs-2020-challenge-local/blob/5d7832f17cbbcb1096e4457d7291eebf1e49f540/solution_app/query2.py#L90-L91

Hi,
Why the sample solution sets all the out of order data points to be 2? Is there any special reason for the value 2?
And is there any reason why you do padding instead of actually calculate based on the partial data or have a buffer to wait?

Do we need to get the exact output of sample solution for Q2 also? We have to follow that in Q1, right?

Thanks,
Zongshun Zhang

**Comment by Zongshun96** [comment]
Sorry, I didn't see the other post about this question. Can we merge this issue with the other one?
https://github.com/dmpalyvos/debs-2020-challenge-local/issues/13

Thanks,
Zongshun Zhang

**Comment by vincenzo-gulisano** [comment]
Hi,
there is no special reason. This is a sample baseline that does not wait for any late arriving data and replaces missing data with 2.0. The baselines for Query 1 and Query 2 are only given to show participants how to retrieve data and return results.
