### ISSUE TITLE
[Query 1] Does the first element in result matter?

### ISSUE THREAD

**Issue by jin-qin** [dmpalyvos/debs-2020-challenge-local#15]
The result is `[s, d, event_s]`, does `s` matter? If we can make `d, event_s` correct but different `s`, will that be ok?

---
Best regards,
Jing Qin

**Comment by vincenzo-gulisano** [comment]
Hi,
`s` is used by the grader to check for the correctness of your results. Hence, it matters.

**Comment by jin-qin** [comment]
But we found something really confused us, would you mind clarifying it?

In codes, the `window2` will be reset if an event is not detected and `size(window2) > 100`, however, in the description on the website, it says the earliest pair of features is removed.

---
Best regards,
Jing Qin
