### ISSUE TITLE
Need clarification for Window2 strategy

### ISSUE THREAD

**Issue by jin-qin** [dmpalyvos/debs-2020-challenge-local#16]
We found something really confused us, would you mind clarifying it?

In codes, the `window2` will be reset if an event is not detected and `size(window2) > 100`, however, in the description on the website, it says the earliest pair of features is removed (does it mean removing the first element in `window2`?).

[Related issue](https://github.com/dmpalyvos/debs-2020-challenge-local/issues/15)

---
Best regards,
Jing Qin

**Comment by dmpalyvos** [comment]
Hi Jing,

Could you clarify a bit? Does this happen in the baseline solution? In which file/line?

Kind Regards,
Dimitris

**Comment by jin-qin** [comment]
Hi Dimitris,

It's at `line 136` in `query1.py`. But in the description on the website, it says the earliest pair of features is removed.

---
Best regards,
Jing Qin

**Comment by Zongshun96** [comment]
Hi,
We are having the similar concern here. 
The Window2 logic mentioned on your [main page](https://2020.debs.org/call-for-grand-challenge-solutions/) seems easier for optimization, as we don't need to wait for event detection result and then decide how to process X or the window2.

Thanks,
Zongshun Zhang

**Comment by vincenzo-gulisano** [comment]
Dear Jing Qin and Zongshun Zhang,
thank you for spotting the difference between the page and the baseline.
The correct way to go is that of the baseline. We will now change the description in the main page from "if an event is not detected and window W2 contains more than 100 elements, the earliest pair of features is removed" to "if an event is not detected and window W2 contains more than 100 elements, the window is then emptied."
