### ISSUE TITLE
Docker Compose Evaluation

### ISSUE THREAD

**Issue by EthanTGo** [dmpalyvos/debs-2020-challenge-local#18]
I was wondering whether it's possible to modify the docker-tempolate.yml. In our solution, we want to use two separate API for our solution?

**Comment by dmpalyvos** [comment]
Hi,

Could you clarify a bit on what you would like to do?

Kind Regards,
Dimitris

**Comment by Zongshun96** [comment]
Hi,
It was more like something we wanted to make sure.

The submission in addition to pushing a solution image to docker hub would include a docker-compose.yml to setup services which can be designed by ourselves, right? It looks like there is a [template](https://github.com/dmpalyvos/debs-2020-challenge-local/blob/master/platform-docker-compose-template.yml) in this repository but that is just an example, correct?
When we says "designed by ourselves", it is about the services other than the grader. Say if we got multiple services or specify commend that is also fine, right?

Thanks,
Zongshun Zhang

**Comment by dmpalyvos** [comment]
Hi,

The platform does not support the submission of custom docker-compose.yml files. The whole functionality of the solution should be included inside a single docker container, which will be executed according to the [template file](https://github.com/dmpalyvos/debs-2020-challenge-local/blob/master/platform-docker-compose-template.yml). 

Kind Regards,
Dimitris

**Comment by mdesilva** [comment]
Some projects need additional services to run, and cannot run on one solution service alone. Due to this need, can we please submit our own template files ? Thank you in advance for your extended consideration

**Comment by dmpalyvos** [comment]
Hi,

Unfortunately the evaluation platform architecture does not support custom docker-compose.yml files or running multiple containers at the same time. Furthermore such a solution would not be uniform across teams that have already provided solutions building on the available yml file. 

If you want, you are welcome to send your docker-compose.yml in case we have any ideas for possible workarounds using only one container. You can send the file privately, to the emails where you register your Grand Challenge solution (see the "Evaluation platform" email for details). 

Kind Regards,
Dimitris
