### ISSUE TITLE
Where can we access results.json ?

### ISSUE THREAD

**Issue by mdesilva** [dmpalyvos/debs-2020-challenge-local#19]
When evaluating locally using the docker container, it says that it wrote the results to  ./results.json. However, I cannot find the file in the directory of the docker container. Where can I find that file ?

**Comment by dmpalyvos** [comment]
Hi,

The results are saved in the / directory of the container, which is not mounted on the host. If you want to see the file, you can save the results in a mounted directory, e.g., /dataset, by adding the  line `RESULTS_PATH: "/dataset"` in your docker-compose.yml, after the line `DATASET_PATH: ...`

However, note that the results are just the scores that the grader prints in stdout. Also, if you do the above, you will need to remove the results.json between subsequent executions.

Kind Regards,
Dimitris
