### ISSUE TITLE
Conflicting backward pass procedures

### ISSUE THREAD

**Issue by mdesilva** [dmpalyvos/debs-2020-challenge-local#21]
In the python solution code, the backwards pass removes the oldest datapoint in each iteration. In the [query description](https://2020.debs.org/call-for-grand-challenge-solutions/), it tells us to remove the latest data tuple in each iteration. What implementation do we follow ?

**Comment by vincenzo-gulisano** [comment]
Please refer to the python solution code as the baseline, and sorry for the confusion.
