### ISSUE TITLE
Grader randomly 'missing' results

### ISSUE THREAD

**Issue by mdesilva** [dmpalyvos/debs-2020-challenge-local#22]
The grader says it is missing random results, those results usually belonging to the s range of 490-499. However, I believe my program is posting the results correctly. How can we debug this ?

**Comment by mdesilva** [comment]
Also, when is the grader going to be updated with #6 ? When running the provided python solution code, it says it is missing the result (317,1,314.5), even though it provided the result (317,1,314).

**Comment by dmpalyvos** [comment]
Replying to your second question (because it might be related to the first): How are you evaluating your solution? Please make sure you are using the latest datasets that have been provided to you (which include the fix to the issue you mention).

**Comment by jin-qin** [comment]
Try checking your codes, we got the same problem but fixed by double-checking our codes.

> The grader says it is missing random results, those results usually belonging to the s range of 490-499. However, I believe my program is posting the results correctly. How can we debug this ?

**Comment by mdesilva** [comment]
Where can we find the latest dataset?

**Comment by mdesilva** [comment]
> Try checking your codes, we got the same problem but fixed by double-checking our codes.
> 
> > The grader says it is missing random results, those results usually belonging to the s range of 490-499. However, I believe my program is posting the results correctly. How can we debug this ?

What was the issue that you faced ? It seems like all the requests are going through in my persepctive.

**Comment by mdesilva** [comment]
The issue was that my solution implementation was sending an extra get request after it received the last record, but before the last result was posted, therefore triggering the grader to grade early.
