### ISSUE TITLE
Does the first element in result really matter a lot?

### ISSUE THREAD

**Issue by jin-qin** [dmpalyvos/debs-2020-challenge-local#23]
As we understand, the first element `s` means when we detected the event, but we read the grader codes and found if we give the wrong `s`, but correct `event_s` we will get 0 scores for this event, is it reasonable?

At least for Query2, it will be easy to get a different `s`.

---
Best regards,
Jing Qin

**Comment by vincenzo-gulisano** [comment]
Dear Jing Qin,
the `s` need to be correct (i.e., it needs to refer to the correct batch) in order to the grader to understand which is the `event_ts` your response refers to. If the `s` you provide is not know or refers to a different batch, then the `event_ts` of your solution is not correct.

**Comment by jin-qin** [comment]
Hi Vincenzo,

Thank you for your reply.

What I mean is, can `s` be a rank for grading?

Since from our understanding so far, `s` is referred to `when the event is detected`, it depends on the `window2` size and the window start index, but if we can get the correct `event_ts` but different `s`, maybe this could make sense since `when the event is detected` can also be graded as a rank (if it's possible), i.e. if we announce this event too late, this event does make no sense, but if we detect it a little bit late, this event may still work, but maybe fewer scores?

Although we can make `s` correct right now, we still want to discuss more about it since it's a little bit confusing to us. For this challenge, if it is the rule, we can understand, but for this problem we are trying to solve in this challenge, we are not very sure if this `s` does matter a lot or it can be graded as one of the ranks.

---
Best regards,
Jing Qin

**Comment by vincenzo-gulisano** [comment]
Hi,
at this point in the challenge, we cannot change how scores / grading works.
I am still unsure, nonetheless, about the aspect you mention. 
If you correctly identify the `event_ts` of an event in batch `i` you can still get a score for it (accuracy), but you need to provide `event_ts` no more than 10 batches late if you want the timeliness score to be > 0. The `s` you provide with `event_ts` needs nonetheless to be correct for the grader to understand which batch `event_ts` refers to. 
If you want, please create a small example and we can discuss further.

**Comment by jin-qin** [comment]
Thank you for your explanation.
