### ISSUE TITLE
The weight of ranks

### ISSUE THREAD

**Issue by jin-qin** [dmpalyvos/debs-2020-challenge-local#24]
Would you mind give the weight of ranks of both Query 1 and Query 2 so that we can know which rank is more important?

---
Best regards,
Jing Qin

**Comment by vincenzo-gulisano** [comment]
correctness and speed (Q1) as well as timeliness and accuracy (Q2) are all equally weighted. The overall final rank is calculated as the sum of all rankings for both queries.

**Comment by jin-qin** [comment]
Many thanks, clear explanation.
