### ISSUE TITLE
Do we have to trigger the grader ourselves ?

### ISSUE THREAD

**Issue by mdesilva** [dmpalyvos/debs-2020-challenge-local#25]
Do we have to trigger the grader ourselves to verify our results after we post the last result ?

**Comment by mdesilva** [comment]
Our solution fetches the get requests for the records faster than the results are outputted. So, our processor doesn't necessarily know when it has seen all the records, and therefore can't safely submit the extra get request to get the score. This is why we are wondering if we need to trigger the extra get request ourselves.

**Comment by dmpalyvos** [comment]
Hi,

Yes, you have to trigger it manually. Take a look at this discussion, in case it helps:
https://github.com/dmpalyvos/debs-2020-challenge/issues/3

Without knowing your exact architecture, my first suggestion would be to send a special data item to the processor to signify the end of the data and have the processor perform the last get request.

Let me know if you have further questions! 

Kind Regards,
Dimitris

**Comment by mhendrick98** [comment]
We were able to figure it out - thanks!
