### ISSUE TITLE
Evaluation Platform Inftrastucture Specification

### ISSUE THREAD

**Issue by Zongshun96** [dmpalyvos/debs-2020-challenge-local#3]
Hi,
    I was wonderring if anyone can share some information about the infrastructure that out solution is going to test on? Or where can we find those information? For example number of virtual CPU cores, memory size and whether it would be SSD or HDD based.

Thanks,
Zongshun Zhang

**Comment by Hannajd** [comment]
Hello,
Your solution will be run on an Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz with 2 sockets, 8 cores per socket, and 2 threads per core.
The system has 32K L1d and 32K L1i cache. L2 and L3 cache are 256K and 20480K, respectively.

Best,

**Comment by dmpalyvos** [comment]
No.

**Comment by Zongshun96** [comment]
Following on this topic, 
1 how much memory will the solution run on?
2 is it an SSD based system? 

Just to understand the system. We haven't decide the implementation yet.

Thanks,
Zongshun Zhang

**Comment by Hannajd** [comment]
Hi,
The disk is SSD and the main memory is 128GB.
