### ISSUE TITLE
Float third value in out.csv

### ISSUE THREAD

**Issue by jin-qin** [dmpalyvos/debs-2020-challenge-local#6]
Hi, we are quite confused by the data in `out.csv` of the **smaller** dataset. There is a float third value in it which is `(317,1,314.5)`, would you mind give a clarification for it, we don't understand why the 3rd value is a float.

**Comment by vincenzo-gulisano** [comment]
Hi,
The float value is due to the command
mean_event_index = np.mean([event_interval_indices[0], event_interval_indices[1]])
in the baseline.

We will push an update so that we round the value.
Thanks for pointing this out

**Comment by Tobii42** [comment]
Hi,

now I am a bit confused. Why will the value be better if it is rounded? Isn't the mean value the correct value there?

And, if you change the code to round the values, will you also update the data sets for the Grader, so that they reflect the new "correct" results?

Greetings

**Comment by jin-qin** [comment]
> Hi,
> 
> now I am a bit confused. Why will the value be better if it is rounded? Isn't the mean value the correct value there?
> 
> And, if you change the code to round the values, will you also update the data sets for the Grader, so that they reflect the new "correct" results?
> 
> Greetings

`mean_event_index` is an event index, should not be a float.

**Comment by Tobii42** [comment]
Ok, I see and thank you for your answer!

@vincenzo-gulisano To update our solution against this new requirement I have a few questions. Will you round up or down? Will you update the test data sets accordingly and also push an update for the python-solution? And will the grader online platform test against the new, corrected solution?

Greetings

**Comment by Leinadj** [comment]
@jin-qin   As usually timestamps are compared, having a float index is perfectly fine if you convert it back to a timestamp.  But we will adapt it for the grand challenge evaluation to make things clearer for you.

**Comment by mhendrick98** [comment]
@vincenzo-gulisano  Just wanted to follow up on this. To clarify, is the final answer 314 or 315? Is the new version rounding up or down?

**Comment by vincenzo-gulisano** [comment]
Hi,
the latest commit uses `math.floor` (both for Q1 and Q2)
