### ISSUE TITLE
Constraint 3 and Loss calculation

### ISSUE THREAD

**Issue by mbr-rbm** [dmpalyvos/debs-2020-challenge-local#7]
Hello,

We are a bit confused by the handling of the third constraint (of M3) and the loss calculation. As far as we understood, the third constraint (no overlaps in time domain) is an optimal situation without any losses. But since data may not be optimal, which means to have e.g. points of C2 in the time domain of C1, loss is calculated and a maximum loss is acceptable.

In your calculation, you take the third constraint hard: no overlaps. Then, you calculate the loss by counting the outliers (cluster -1) in the two time domians and in the change interval. But that is definitely NOT how the loss is defined:

"The loss for a signal segment X and two clusters C1 and C2 is defined as follows,
                               it counts the number of samples that need to be corrected in order for the segment
                               to match the event model:
                               L(X) = a + b + c with
                               a: number of samples n from C2 with n <= u, with u being the lower bound of
                               the event_interval_t
                               b: number of samples n from C1 with n >= v, with v being the upper bound of
                               the  event_interval_t
                               c: number of samples n between u < n < v, so number of samples n in the event_interval_t that
                               belong to C1 or C2, i.e. to the stationary signal."

We would really appreciate to help us out with this problem.

**Comment by Leinadj** [comment]
Hello,

You are right, you could also treat the constraint to  be a soft one and then regulate this via the loss.
In case of noisy data, you would want to avoid allowing overlaps, so this was a design decision to make the constraint hard. Of course you can also enforece it with a respective loss-threshold.

Regarding the loss calculation, it is implemented in the respective method according to the paper,
so I do not understand your remark.

**Comment by mbr-rbm** [comment]
Hello and thanks for your response,

I think, I was a bit confused. So, to check, whether I understand it now correctly: You take the third constraint hard and, therefore, it would not be necessary to compute the loss, because it is always 0 after checking constraint three.

One question remains. You make the assumption that there must be noise/outliers within the change interval. Can you please explain, why? Because, when I read the publication about the algorithm and take a look at Figure 1c and 1d, there is not necessarily noise in the change interval. It can be a third cluster.

Thanks in advance for your effort
Michael

**Comment by Leinadj** [comment]
Hello Michael,

sorry for the late reply, I did not see your response:
1. You are right: the third constraint ensures we have no overlap in the time domain between to clusters. This is enforced for the reasons mentioned before. The loss can be non-zero despite this:
In the loss calculation c can be non-zero, as there can be an overlap of one of the clusters with the event-interval.

2. Except for the example in Figure 1a, the change interval always belongs to cluster 0 (-1 in the implementation). This makes perfect sense, as we consider the change between two states not to be a state on its own. The changes are rapid. Hence, the state-transition is defined to be the noise in between two "proper" states.

Let me know if you need further help.

**Comment by Leinadj** [comment]
@mbr-rbm  Do you still need help with this or can the thread be closed?

**Comment by mbr-rbm** [comment]
Also sorry for my late reply. It is all a bit chaotic these days.

To 1. Do you mean a third cluster having an overlap with the event interval? If so, I would agree in general. But the mathematical definition of the loss only takes the two clusters into account. If not, I'm sorry, but I don't get how points of, e.g. the first cluster, can be in the change interval if the beginning of the change interval is defined by the last point of that cluster.

To 2. I disagree with your interpretation. I quote the description of the figure from the paper: "(c) shows a repeated pattern of spikes that eventually cluster in C3. Finally, (d) shows high fluctuations in stationary segments leading to the third cluster C3 as well." And C3 is not the outlier cluster.

Best,
Michael

**Comment by Leinadj** [comment]
No worries, same here :)
So first, regarding your second point: Yes, but the event transition is still the noise cluster. As you can see, the third cluster belongs to state before the event, as well as to the state after the event, especially in figure (c). It does not represent the event. The event cluster is still the noise cluster., this can be clearly seen looking at the y-axis (the clusters) of the graph. The event transition interval is in cluster 0 .

**Comment by Leinadj** [comment]
Regarding remark 1: That is true indeed, so by taking the third model constraint hard, looking at the loss is redundant. You you also enforce this criteria via the loss if you want to.

**Comment by mbr-rbm** [comment]
Ok, thanks for clarification
