### ISSUE TITLE
Hint for Last Element

### ISSUE THREAD

**Issue by Tobii42** [dmpalyvos/debs-2020-challenge-local#8]
Hi,

Currently I am working on the second query with the out-of-order elements. The simple approach is that I let my output lag behind the current input so that I can wait for elements that arrive later. Unfortunately, the Grader creates the results as soon as I receive the 404 response showing me that the input stream ends. That way the Grader misses a few of my results (depending on the time that I let my results lag behind these can be a lot).

If I would know that I received the last element before the Grader verifies the results, I could flush the remaining elements and then start the verification (e.g. by doing the last get and receive the 404).

Would that be a possible extension to the grader to send a special "last" element before the 404 that starts the verification? Or did I miss an idea in the Grader verification process that would solve my problem?

Greetings

**Comment by vincenzo-gulisano** [comment]
Hi,
your point is correct. We will push an update in the next days so that before the 404 a final special element is also delivered.

**Comment by Tobii42** [comment]
Thanks a lot!
