### ISSUE TITLE
debs-2020-challenge-grader source code

### ISSUE THREAD

**Issue by Zongshun96** [dmpalyvos/debs-2020-challenge-local#9]
Hi,
Can you open source the grader code (or share a pointer where it is already posted)? We think this can help us debug on what is sent and understand how would the grader calculate those metrics.

For now, in q1, we are getting error,

```
ERROR: Missing results!
(0, 0, -1.0)
```

We are wonderring whether it is about data type or format we send to grader.

Thanks,
Zongshun Zhang

**Comment by dmpalyvos** [comment]
Hi,

The error means that you have not sent a correct result for the first batch (as expected by the out.csv). In case you need the code of the grader to further debug the system, you can find it here: https://github.com/dmpalyvos/debs-2020-challenge

Note that this is the development & test repository so it might not always reflect the stable version of the grader and baseline-solution.

Kind Regards,
Dimitris

**Comment by Zongshun96** [comment]
Thanks! That solved my problem.

Best,
Zongshun Zhang
